#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Bump the minor version, commit, tag, and create a GitHub release.

.DESCRIPTION
    1. Reads the current version from flutter_client/pubspec.yaml (e.g. 0.18.0+1).
    2. Increments the minor component and resets patch to 0 (e.g. 0.19.0+1).
    3. Updates pubspec.yaml.
    4. Commits the change and pushes to origin/main.
    5. Creates an annotated git tag (e.g. v0.19.0) and pushes it.
    6. Creates a GitHub release, with notes generated by
       scripts/release_notes.py from the commits since the previous tag.

.PREREQUISITES
    - gh CLI installed and authenticated (gh auth login).
    - git configured with push access to origin.
    - python on PATH (for the release notes).
    - Optional, for -Polish: pip install anthropic, and ANTHROPIC_API_KEY set.

.EXAMPLE
    .\bump_version_and_release.ps1            # minor bump (0.36.0 -> 0.37.0)
    .\bump_version_and_release.ps1 -Patch     # patch bump (0.36.0 -> 0.36.1)
    .\bump_version_and_release.ps1 -DryRun    # print the notes, change nothing
    .\bump_version_and_release.ps1 -Polish    # add an LLM highlights paragraph
#>
param(
    [switch]$DryRun,
    [switch]$Patch,
    [switch]$Polish
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$PUBSPEC = Join-Path $PSScriptRoot "flutter_client\pubspec.yaml"

function Die([string]$msg) {
    Write-Host ""
    Write-Host "ERROR: $msg" -ForegroundColor Red
    exit 1
}

function Step([string]$msg) {
    Write-Host ""
    Write-Host ">> $msg" -ForegroundColor Cyan
}

# -- 1. Read and parse current version -----------------------------------------
Step "Reading current version from pubspec.yaml"

$pubspecContent = Get-Content $PUBSPEC -Raw
if ($pubspecContent -notmatch '(?m)^version:\s*(\d+)\.(\d+)\.(\d+)\+(\d+)') {
    Die "Could not parse 'version: X.Y.Z+N' from pubspec.yaml"
}
$major    = [int]$Matches[1]
$minor    = [int]$Matches[2]
$patchNum = [int]$Matches[3]
$build    = [int]$Matches[4]

$oldVersion = "$major.$minor.$patchNum+$build"

if ($Patch) {
    $newVersion = "$major.$minor.$($patchNum + 1)+$build"
    $newTag     = "v$major.$minor.$($patchNum + 1)"
} else {
    $newVersion = "$major.$($minor + 1).0+$build"
    $newTag     = "v$major.$($minor + 1).0"
}

# The previous tag comes from git, not from pubspec.yaml. Deriving it from the
# version ("v$major.$minor.$patchNum") silently produced the wrong commit range
# whenever a tag was cut by hand or pubspec drifted, and the old fallback then
# used an arbitrary "last 30 commits".
git fetch --tags 2>$null
$oldTag = (git describe --tags --abbrev=0 2>$null)
if (-not $oldTag) {
    Write-Host "  Note: no tags found -- notes will cover the full history" -ForegroundColor Yellow
}

Write-Host "  $oldVersion  ->  $newVersion  (tag: $oldTag -> $newTag)"

# -- 2. Build the release notes ------------------------------------------------
# Ahead of the clean-tree check so -DryRun can preview the notes mid-work: the
# range is HEAD-based, so uncommitted changes can't affect what it produces.
Step "Writing release notes for $oldTag..$newTag"
# scripts/release_notes.py groups the commits by type and audience, drops merge
# commits and version bumps, and links issue refs. Preview any range without
# releasing:  python scripts/release_notes.py --from v0.46.9 --to HEAD
$notesArgs = @(
    (Join-Path $PSScriptRoot "scripts\release_notes.py"),
    "--to", "HEAD", "--version", $newTag
)
if ($oldTag) { $notesArgs += @("--from", $oldTag) }
if ($Polish) { $notesArgs += "--polish" }

# Python writes UTF-8 bytes (the headings carry emoji); tell PowerShell to read
# them as UTF-8 rather than the console's default code page.
$prevEncoding = [Console]::OutputEncoding
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
try {
    $releaseBody = (& python @notesArgs) -join "`n"
} finally {
    [Console]::OutputEncoding = $prevEncoding
}
if ($LASTEXITCODE -ne 0 -or -not $releaseBody) { Die "release_notes.py failed." }

Write-Host ""
Write-Host $releaseBody

if ($DryRun) {
    Write-Host ""
    Write-Host "[DryRun] Notes above. No changes made." -ForegroundColor Yellow
    exit 0
}

# -- 3. Ensure working tree is clean -------------------------------------------
Step "Checking working tree"
$status = git status --porcelain 2>&1
# Allow only pubspec.yaml being modified (edge case: re-run after partial failure)
$dirty = $status | Where-Object { $_ -notmatch '^\s*M\s+flutter_client/pubspec\.yaml' }
if ($dirty) {
    Write-Host "  Uncommitted changes detected:" -ForegroundColor Yellow
    $dirty | ForEach-Object { Write-Host "    $_" }
    Die "Commit or stash your changes before bumping the version."
}

# -- 4. Update pubspec.yaml ----------------------------------------------------
Step "Updating pubspec.yaml to $newVersion"
$updated = $pubspecContent -replace "(?m)^(version:\s*)$([regex]::Escape($oldVersion))", ('${1}' + $newVersion)
Set-Content -Path $PUBSPEC -Value $updated -NoNewline

# -- 5. Commit -----------------------------------------------------------------
Step "Committing version bump"
git add $PUBSPEC
git commit -m "chore: bump version to $newTag"
if ($LASTEXITCODE -ne 0) { Die "git commit failed." }

# -- 6. Push commit ------------------------------------------------------------
Step "Pushing commit to origin"
git push origin HEAD
if ($LASTEXITCODE -ne 0) { Die "git push failed." }

# -- 7. Create and push annotated tag ------------------------------------------
Step "Tagging $newTag"
git tag -a $newTag -m "Release $newTag"
if ($LASTEXITCODE -ne 0) { Die "git tag failed." }
git push origin $newTag
if ($LASTEXITCODE -ne 0) { Die "git push tag failed." }

# -- 8. Create GitHub release --------------------------------------------------
Step "Creating GitHub release $newTag"
# --notes-file (rather than --notes $releaseBody) avoids passing a multi-line
# string as a raw CLI argument: on Windows, PowerShell's native-argument
# marshaling can split it across multiple argv entries at the embedded
# newlines, and gh then tries to glob-expand a stray trailing line as an
# asset filename (e.g. a commit subject containing "(...)").
$notesFile = Join-Path ([System.IO.Path]::GetTempPath()) "viewtrip-release-notes-$newTag.md"
Set-Content -Path $notesFile -Value $releaseBody -NoNewline
try {
    gh release create $newTag `
        --title "ViewTripWeb $newTag" `
        --notes-file $notesFile
    if ($LASTEXITCODE -ne 0) { Die "gh release create failed." }
} finally {
    Remove-Item -Path $notesFile -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "==========================================" -ForegroundColor Green
Write-Host "  Released $newTag" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green
Write-Host ""
