"""Alembic migration tests — the CI `alembic upgrade head && alembic check` step,
run locally so migration/model drift is caught before it reaches GitHub.

Why this exists: a column was added to a migration as `sa.Text()` while the
SQLModel field maps to `AutoString()` (VARCHAR). Everything "worked" locally and
in prod (SQLite treats TEXT and VARCHAR identically), but `alembic check` flags
the type mismatch and the CI Tests job went red. The unit/integration tests never
exercised Alembic, so nothing local caught it. These tests close that gap.

Each test builds a throwaway SQLite database from the migrations alone, so it is
hermetic and never touches the developer's real db.
"""
import os
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

_PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _alembic_config(db_path: Path) -> Config:
    """Alembic Config pointed at a throwaway SQLite file.

    env.py honours the DATABASE_URL env var over alembic.ini, so we set it for
    the duration of the test rather than mutating the ini.
    """
    cfg = Config(str(_PROJECT_ROOT / "alembic.ini"))
    cfg.set_main_option("sqlalchemy.url", f"sqlite:///{db_path.as_posix()}")
    return cfg


@pytest.fixture()
def fresh_db(tmp_path, monkeypatch):
    db_path = tmp_path / "alembic_test.db"
    # env.py reads DATABASE_URL and lets it win; keep it consistent with the cfg.
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{db_path.as_posix()}")
    return db_path


def test_upgrade_head_succeeds(fresh_db):
    """Every migration applies cleanly from scratch (catches broken DDL/backfills)."""
    cfg = _alembic_config(fresh_db)
    command.upgrade(cfg, "head")
    assert fresh_db.exists()


def test_models_in_sync_with_migrations(fresh_db):
    """`alembic check` — model metadata must match the migration head.

    Mirrors the CI step exactly: a column added/changed in the model without a
    matching migration (or a migration whose column type drifts from the model,
    e.g. Text vs AutoString) makes autogenerate detect operations and this fails.
    """
    cfg = _alembic_config(fresh_db)
    command.upgrade(cfg, "head")
    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "Model metadata has drifted from the migration head — autogenerate "
            f"would produce new operations:\n{exc}\n"
            "Add a migration (or fix the offending migration's column types) so "
            "`alembic check` is clean. See alembic/versions/."
        )


def test_downgrade_base_succeeds(fresh_db):
    """Migrations are reversible all the way back to base (catches missing downgrades)."""
    cfg = _alembic_config(fresh_db)
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
