"""add_memories

Revision ID: 316b7dd1374b
Revises: ea002876cb8d
Create Date: 2026-04-01 10:21:18.300109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316b7dd1374b'
down_revision: Union[str, Sequence[str], None] = 'ea002876cb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('photos_json', sa.String(), nullable=False),
    sa.Column('geo_mode', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_date'), 'memory', ['date'], unique=False)
    op.create_index(op.f('ix_memory_project_id'), 'memory', ['project_id'], unique=False)
    op.add_column('projectitem', sa.Column('memory_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projectitem', 'memory_id')
    op.drop_index(op.f('ix_memory_project_id'), table_name='memory')
    op.drop_index(op.f('ix_memory_date'), table_name='memory')
    op.drop_table('memory')
    # ### end Alembic commands ###
