"""add project tables

Revision ID: 40655974e9f7
Revises: d19c0b0b1c1e
Create Date: 2026-03-26 18:19:37.106972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40655974e9f7'
down_revision: Union[str, Sequence[str], None] = 'd19c0b0b1c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_info_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('moving_time', sa.Integer(), nullable=False),
    sa.Column('elapsed_time', sa.Integer(), nullable=False),
    sa.Column('total_elevation_gain', sa.Float(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date_local', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('achievement_count', sa.Integer(), nullable=False),
    sa.Column('kudos_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('athlete_count', sa.Integer(), nullable=False),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('pr_count', sa.Integer(), nullable=False),
    sa.Column('total_photo_count', sa.Integer(), nullable=False),
    sa.Column('trainer', sa.Boolean(), nullable=False),
    sa.Column('commute', sa.Boolean(), nullable=False),
    sa.Column('manual', sa.Boolean(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('has_heartrate', sa.Boolean(), nullable=False),
    sa.Column('has_kudoed', sa.Boolean(), nullable=False),
    sa.Column('heartrate_opt_out', sa.Boolean(), nullable=False),
    sa.Column('display_hide_heartrate_option', sa.Boolean(), nullable=False),
    sa.Column('average_speed', sa.Float(), nullable=False),
    sa.Column('max_speed', sa.Float(), nullable=False),
    sa.Column('gear_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('average_heartrate', sa.Float(), nullable=True),
    sa.Column('max_heartrate', sa.Integer(), nullable=True),
    sa.Column('elev_high', sa.Float(), nullable=True),
    sa.Column('elev_low', sa.Float(), nullable=True),
    sa.Column('start_latlng_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_latlng_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary_polyline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('elevation_profile_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_info_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_start_date'), 'activity', ['start_date'], unique=False)
    op.create_index(op.f('ix_activity_type'), 'activity', ['type'], unique=False)
    op.create_index(op.f('ix_activity_user_info_id'), 'activity', ['user_info_id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_info_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('filter_state_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_info_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_index(op.f('ix_project_user_info_id'), 'project', ['user_info_id'], unique=False)
    op.create_table('stravacache',
    sa.Column('user_info_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.Float(), nullable=False),
    sa.Column('activities_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_info_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('user_info_id')
    )
    op.create_table('projectitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('segment_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectitem_project_id'), 'projectitem', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projectitem_project_id'), table_name='projectitem')
    op.drop_table('projectitem')
    op.drop_table('stravacache')
    op.drop_index(op.f('ix_project_user_info_id'), table_name='project')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_activity_user_info_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_type'), table_name='activity')
    op.drop_index(op.f('ix_activity_start_date'), table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
