"""add ImmichToken table

Revision ID: 40f9fd701dfb
Revises: a1f37c2e8b04
Create Date: 2026-08-22 20:15:52.515651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '40f9fd701dfb'
down_revision: Union[str, Sequence[str], None] = 'a1f37c2e8b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('immichtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_info_id', sa.Integer(), nullable=False),
    sa.Column('server_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_info_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('immichtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_immichtoken_user_info_id'), ['user_info_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immichtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_immichtoken_user_info_id'))

    op.drop_table('immichtoken')
    # ### end Alembic commands ###
