"""add_share_token

Revision ID: 572a9bb2d2a8
Revises: 40655974e9f7
Create Date: 2026-03-27 17:31:58.885784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '572a9bb2d2a8'
down_revision: Union[str, Sequence[str], None] = '40655974e9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('share_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_project_share_token'), 'project', ['share_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_share_token'), table_name='project')
    op.drop_column('project', 'share_token')
    # ### end Alembic commands ###
