"""add StravaToken table

Revision ID: d19c0b0b1c1e
Revises: 88d31b1f3613
Create Date: 2026-03-22 23:03:49.804837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd19c0b0b1c1e'
down_revision: Union[str, Sequence[str], None] = '88d31b1f3613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stravatoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_info_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_info_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stravatoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stravatoken_user_info_id'), ['user_info_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stravatoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stravatoken_user_info_id'))

    op.drop_table('stravatoken')
    # ### end Alembic commands ###
