"""add stats_json to project

Revision ID: ea002876cb8d
Revises: ecb730945e37
Create Date: 2026-03-31 14:04:44.358819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea002876cb8d'
down_revision: Union[str, Sequence[str], None] = 'ecb730945e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('stats_json', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'stats_json')
    # ### end Alembic commands ###
